"""
agentic_feedback.py
===================
Agentic LLM layer for the OBE assessment pipeline.

Architecture
------------
This module sits between the Mamdani FIS (fuzzy_engine.py) and the
frontend dashboard.  It receives an AssessmentResult plus the raw UI
scores, automatically extracts the student's specific weak areas, then
sends a structured context to a locally running LM Studio instance and
returns a uniform FeedbackResult.

DATA PRIVACY & ARCHITECTURE DEFENCE
-------------------------------------
1. Zero-Egress Guarantee
   All inference runs on the local machine (LM Studio on the RTX 3050 GPU).
   No student score, name, or identifier is transmitted to any third-party
   cloud API, telemetry endpoint, or analytics service.  The HTTP request
   never leaves 127.0.0.1.

2. Regulatory Compliance by Design
   Because data residency is bound to the physical host:
   • FERPA  — student educational records never leave the institution's device.
   • GDPR   — no personal data crosses a network boundary; no DPA required.
   • COPPA  — minors' assessment data cannot be harvested by ad-tech pipelines.
   This makes the architecture defensible in any IRB or data-governance review.

3. Deterministic Latency
   GPU inference on a local model is immune to cloud rate-limits, quota
   exhaustion, and WAN jitter.  Response time is bounded by the GPU VRAM
   bandwidth, not by network round-trip time.

4. Model Auditability
   The faculty or institution controls exactly which model weights are loaded
   in LM Studio — no opaque model versioning or silent provider-side updates.

Flow
----
  AssessmentResult + UIFuzzyInputs
       │
       ▼
  extract_weak_areas()          — deterministic, score-driven analysis
       │
       ▼
  LMStudioClient.generate()    — POST to localhost:1234/v1/chat/completions
       │
       ▼
  FeedbackResult                — uniform schema regardless of LLM status
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from fuzzy_engine import AssessmentResult
    from ui_bridge import UIFuzzyInputs

# ---------------------------------------------------------------------------
# LM Studio endpoint configuration
# ---------------------------------------------------------------------------
_LM_STUDIO_URL: str = "http://localhost:1234/v1/chat/completions"
_LM_STUDIO_HEALTH_URL: str = "http://localhost:1234/v1/models"

# Timeout (seconds) for the LLM HTTP call.
_REQUEST_TIMEOUT: int = 120

# ---------------------------------------------------------------------------
# JSON Schema for structured output (json_schema response_format mode).
# This version of LM Studio supports "json_schema" and "text" but NOT
# "json_object".  Providing a full schema lets the model know the exact
# shape expected and enforces it at the sampler level.
# ---------------------------------------------------------------------------
_RESPONSE_FORMAT_SCHEMA: dict = {
    "type": "json_schema",
    "json_schema": {
        "name": "obe_feedback",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "breakdown": {"type": "string"},
                "study_schedule": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "week":  {"type": "integer"},
                            "focus": {"type": "string"},
                            "tasks": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                        },
                        "required": ["week", "focus", "tasks"],
                        "additionalProperties": False,
                    },
                },
            },
            "required": ["breakdown", "study_schedule"],
            "additionalProperties": False,
        },
    },
}


# ---------------------------------------------------------------------------
# Uniform result schema
# ---------------------------------------------------------------------------

@dataclass
class FeedbackResult:
    """
    Uniform output schema for the agentic layer.

    Always contains ``breakdown`` and ``study_schedule`` regardless of
    whether the LLM call succeeded or fell back to graceful degradation.
    The frontend can render this without branching on error states.

    Attributes
    ----------
    breakdown : str
        Natural-language analysis of the student's specific deficiencies.
    study_schedule : str | list
        Customised week-by-week study plan generated by the LLM.
    weak_areas : list[str]
        Machine-derived list of weak sub-topics fed into the LLM prompt.
    llm_available : bool
        True if the LM Studio call succeeded; False if fallback was used.
    latency_ms : float
        Wall-clock time of the LLM request in milliseconds.
    model_used : str
        Model identifier echoed from the LM Studio response, or "fallback".
    """
    breakdown: str
    study_schedule: str | list
    weak_areas: list[str]
    llm_available: bool = True
    latency_ms: float = 0.0
    model_used: str = "local-model"

    def to_dict(self) -> dict:
        return {
            "breakdown":      self.breakdown,
            "study_schedule": self.study_schedule,
            "weak_areas":     self.weak_areas,
            "llm_available":  self.llm_available,
            "latency_ms":     round(self.latency_ms, 1),
            "model_used":     self.model_used,
        }


# ---------------------------------------------------------------------------
# Automatic weak-area extraction (deterministic — no LLM required)
# ---------------------------------------------------------------------------

# Score thresholds used to classify each dimension as weak
_WEAK_THRESHOLD    = 50.0   # below this → weak
_MARGINAL_THRESHOLD = 65.0  # below this → marginal (noted but not flagged as critical)


def extract_weak_areas(
    crisp_attainment: float,
    label: str,
    assignment_score: float,
    attendance: float,
    ca: float | None = None,
    lab_work: float | None = None,
    final_exam: float | None = None,
) -> list[str]:
    """
    Derive a prioritised list of specific weak sub-topics from the FIS
    inputs and output — no LLM call is required for this step.

    Logic
    -----
    1. If individual UI components (CA, Lab, Final) are available, compare
       them to identify the weakest academic strand.
    2. Evaluate attendance as an independent dimension.
    3. Map the overall attainment label to foundational gaps if severe.

    Parameters
    ----------
    crisp_attainment : float   — centroid FIS output [0, 100]
    label : str                — linguistic label (Poor / Developing / …)
    assignment_score : float   — composite score fed to FIS [0, 100]
    attendance : float         — attendance percentage [0, 100]
    ca : float | None          — Continuous Assessment score [0, 100]
    lab_work : float | None    — Lab Work score [0, 100]
    final_exam : float | None  — Final Exam score [0, 100]

    Returns
    -------
    list[str]
        Ordered list of weak sub-topic strings, most critical first.
        Returns ["No specific weak areas identified"] when the student
        is performing well across all dimensions.
    """
    weak: list[str] = []

    # ── UI component analysis (most specific — use when available) ─────────
    if ca is not None and lab_work is not None and final_exam is not None:
        components = {
            "Continuous Assessment (quizzes and in-class tests)": ca,
            "Lab Work and practical implementation exercises":     lab_work,
            "Final Examination preparation and revision strategy": final_exam,
        }
        # Sort by score ascending — most critical first
        for name, score in sorted(components.items(), key=lambda x: x[1]):
            if score < _WEAK_THRESHOLD:
                weak.append(f"{name} (score: {score:.1f}/100 — below passing threshold)")
            elif score < _MARGINAL_THRESHOLD:
                weak.append(f"{name} (score: {score:.1f}/100 — marginal, needs improvement)")

        # Identify the single weakest component even if none are below threshold
        if not weak:
            weakest_name, weakest_score = min(components.items(), key=lambda x: x[1])
            if weakest_score < 75.0:
                weak.append(
                    f"{weakest_name} (score: {weakest_score:.1f}/100 — "
                    f"lowest-scoring component, targeted revision recommended)"
                )

    # ── Assignment score composite analysis (xAPI path — no UI components) ─
    elif assignment_score < _WEAK_THRESHOLD:
        weak.append(
            f"Academic engagement and assignment performance "
            f"(composite score: {assignment_score:.1f}/100)"
        )
        if assignment_score < 30.0:
            weak.append(
                "Foundational subject knowledge — core concepts require "
                "re-study before tackling advanced topics"
            )

    # ── Attendance analysis ────────────────────────────────────────────────
    if attendance < _WEAK_THRESHOLD:
        weak.append(
            f"Class attendance and in-person participation "
            f"({attendance:.1f}% — significantly below recommended 75%)"
        )
        weak.append(
            "Missed lecture content and live demonstrations — "
            "requires active catch-up via recorded materials and peer notes"
        )
    elif attendance < _MARGINAL_THRESHOLD:
        weak.append(
            f"Attendance consistency ({attendance:.1f}% — "
            f"borderline; risk of missing cumulative lecture dependencies)"
        )

    # ── Overall attainment severity ────────────────────────────────────────
    if label in ("Poor", "Developing"):
        weak.append(
            "Time management and structured independent study habits — "
            "critical for students in the lower attainment bands"
        )
    if label == "Poor":
        weak.append(
            "Prerequisite knowledge gaps — a diagnostic review of "
            "foundational topics is strongly recommended before progressing"
        )

    if not weak:
        return ["No specific weak areas identified — student is performing well across all assessed dimensions"]

    return weak


# ---------------------------------------------------------------------------
# Robust JSON extraction helper
# ---------------------------------------------------------------------------

def _extract_json(content: str) -> dict:
    """
    Parse a JSON object from LLM output robustly.

    Strategy (tried in order):
    1. ``json.loads(strict=False)`` on the raw content — handles embedded
       control characters (newlines, tabs) inside string values, which is
       the most common cause of JSONDecodeError from smaller models.
    2. Strip markdown fences (```json ... ```) and retry.
    3. Regex-extract the outermost ``{...}`` block and retry — handles
       models that emit preamble text before the JSON object.

    Raises
    ------
    json.JSONDecodeError
        If all three strategies fail.
    """
    import re as _re

    # Strategy 1: strict=False tolerates literal control chars in strings
    try:
        return json.loads(content, strict=False)
    except json.JSONDecodeError:
        pass

    # Strategy 2: strip markdown fences
    stripped = content.strip()
    if stripped.startswith("```"):
        match = _re.search(r"```(?:json)?\s*([\s\S]+?)```", stripped)
        if match:
            try:
                return json.loads(match.group(1).strip(), strict=False)
            except json.JSONDecodeError:
                pass

    # Strategy 3: extract outermost { ... } block
    match = _re.search(r"\{[\s\S]*\}", content)
    if match:
        return json.loads(match.group(0), strict=False)

    # All strategies exhausted — let the caller handle it
    raise json.JSONDecodeError(
        "No valid JSON object found in LLM output", content, 0
    )


# ---------------------------------------------------------------------------
# LM Studio client
# ---------------------------------------------------------------------------

class LMStudioClient:
    """
    Thin HTTP client for LM Studio's OpenAI-compatible `/v1/chat/completions`
    endpoint.  Uses only the standard library (`urllib`) so no extra
    dependency is required beyond what is already in requirements.txt.

    All traffic is to 127.0.0.1 — nothing leaves the local machine.
    """

    def __init__(
        self,
        url: str = _LM_STUDIO_URL,
        timeout: int = _REQUEST_TIMEOUT,
    ) -> None:
        self.url     = url
        self.timeout = timeout

    def is_available(self) -> bool:
        """
        Probe the LM Studio /v1/models endpoint for a quick health check.
        Returns True if LM Studio is running and has a model loaded.
        """
        try:
            req = urllib.request.Request(_LM_STUDIO_HEALTH_URL)
            with urllib.request.urlopen(req, timeout=3) as resp:
                return resp.status == 200
        except Exception:
            return False

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.65,
    ) -> tuple[dict, str, float]:
        """
        Send a chat completion request and return the parsed response.

        Parameters
        ----------
        system_prompt : str
            Instruction context given to the model.
        user_prompt : str
            The actual assessment data payload.
        temperature : float
            Sampling temperature. 0.65 balances creativity with JSON
            structure compliance for instruction-tuned models.

        Returns
        -------
        tuple[dict, str, float]
            (parsed_json_dict, model_id_string, latency_ms)

        Raises
        ------
        urllib.error.URLError
            If LM Studio is unreachable (not running, wrong port, etc.)
        json.JSONDecodeError
            If the model output is not valid JSON despite response_format.
        ValueError
            If the response structure is missing expected OpenAI fields.
        """
        import re as _re

        # Three attempts in priority order:
        #   1. json_schema  — structured output enforced at sampler level (best)
        #   2. text         — plain text, we extract JSON ourselves (wide compat)
        #   3. no key       — omit response_format entirely (last resort)
        attempts = [
            {"response_format": _RESPONSE_FORMAT_SCHEMA},
            {"response_format": {"type": "text"}},
            {},
        ]

        last_exc: Exception | None = None

        for extra in attempts:
            payload: dict = {
                "model": "local-model",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": user_prompt},
                ],
                "temperature": temperature,
                **extra,
            }

            data = json.dumps(payload).encode("utf-8")
            req  = urllib.request.Request(
                self.url,
                data=data,
                headers={"Content-Type": "application/json"},
                method="POST",
            )

            try:
                t0 = time.perf_counter()
                with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                    raw     = resp.read().decode("utf-8")
                    latency = (time.perf_counter() - t0) * 1000

                response_json = json.loads(raw)

                if "choices" not in response_json or not response_json["choices"]:
                    raise ValueError(
                        f"Unexpected LM Studio response structure: "
                        f"{list(response_json.keys())}"
                    )

                content  = response_json["choices"][0]["message"]["content"]
                model_id = response_json.get("model", "local-model")

                parsed = _extract_json(content)
                return parsed, model_id, latency

            except urllib.error.HTTPError as http_exc:
                body = ""
                try:
                    body = http_exc.read().decode("utf-8")[:300]
                except Exception:
                    pass
                last_exc = http_exc
                fmt = extra.get("response_format", {}).get("type", "none")
                print(
                    f"[agentic] response_format={fmt!r} rejected "
                    f"(HTTP {http_exc.code}) — trying next mode. Body: {body}"
                )
                continue

            except urllib.error.URLError as url_exc:
                last_exc = url_exc
                raise   # network failure — no point retrying

        raise RuntimeError(
            f"generate() exhausted all response_format attempts. "
            f"Last error: {last_exc}"
        )


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are an expert AI educational consultant embedded in an Outcome-Based \
Education (OBE) assessment system. You receive a student's defuzzified \
attainment score from a Mamdani Fuzzy Inference System along with their \
specific identified weak areas.

Your response MUST be a valid JSON object with exactly two keys:

1. "breakdown" (string): A 2–4 paragraph natural language analysis that:
   - Explains what the FIS attainment score means in OBE terms
   - Pinpoints the specific sub-topic deficiencies listed in the weak areas
   - Explains the likely root causes (e.g., attendance gaps causing cumulative \
knowledge loss, practical skills lagging behind theory, etc.)
   - Is written directly to the faculty reviewing this report

2. "study_schedule" (list of objects): A week-by-week plan, each entry being \
an object with keys "week" (integer), "focus" (string), and "tasks" \
(list of strings). Generate 4 weeks minimum; 6 weeks if the student is in \
the Poor or Developing band.

Return ONLY the JSON object. No markdown fences, no preamble text.\
"""


def _build_user_prompt(
    crisp_attainment: float,
    label: str,
    assignment_score: float,
    attendance: float,
    weak_areas: list[str],
    fired_rules: list[str],
    ca: float | None,
    lab_work: float | None,
    final_exam: float | None,
) -> str:
    lines = [
        "=== STUDENT ASSESSMENT REPORT ===",
        f"FIS Attainment Score      : {crisp_attainment:.2f}%",
        f"Attainment Classification : {label}",
        f"Composite Assignment Score: {assignment_score:.2f}/100",
        f"Attendance Percentage     : {attendance:.1f}%",
    ]

    if ca is not None:
        lines += [
            "",
            "=== GRADE COMPONENT BREAKDOWN ===",
            f"Continuous Assessment : {ca:.1f}/100  (weight 30%)",
            f"Lab Work              : {lab_work:.1f}/100  (weight 20%)",
            f"Final Exam            : {final_exam:.1f}/100  (weight 50%)",
        ]

    lines += [
        "",
        "=== IDENTIFIED WEAK AREAS ===",
    ]
    for i, area in enumerate(weak_areas, 1):
        lines.append(f"{i}. {area}")

    if fired_rules:
        lines += [
            "",
            "=== FUZZY RULES THAT FIRED (diagnostic) ===",
        ]
        for rule in fired_rules[:6]:   # cap at 6 to avoid token bloat
            lines.append(f"• {rule}")

    lines += [
        "",
        "Generate the breakdown and study_schedule JSON now.",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Graceful degradation fallback (LM Studio offline)
# ---------------------------------------------------------------------------

def _build_fallback_feedback(
    crisp_attainment: float,
    label: str,
    weak_areas: list[str],
) -> FeedbackResult:
    """
    Return a rule-based static feedback object when the LLM is unavailable.
    Uses the same FeedbackResult schema so the frontend never needs to branch.
    The ``llm_available`` flag signals the UI to show an offline indicator.
    """
    severity_map = {
        "Poor":         "significantly below the minimum attainment threshold",
        "Developing":   "below the expected attainment level",
        "Satisfactory": "at a satisfactory but improvable level",
        "Good":         "at a good level with room for refinement",
        "Excellent":    "at an excellent level",
    }
    description = severity_map.get(label, "at an undetermined level")

    breakdown = (
        f"The student's FIS-computed attainment score is {crisp_attainment:.2f}%, "
        f"which places them {description} according to the OBE attainment rubric. "
        f"The following areas were algorithmically identified as requiring attention: "
        f"{'; '.join(weak_areas[:3])}. "
        f"Note: Detailed AI-generated feedback is unavailable because LM Studio is "
        f"not currently running on this machine. Start LM Studio and load a model "
        f"to enable personalised narrative feedback."
    )

    weeks = 4 if label in ("Good", "Satisfactory", "Excellent") else 6
    schedule = [
        {
            "week": w,
            "focus": f"Week {w}: Address {weak_areas[min(w - 1, len(weak_areas) - 1)]}",
            "tasks": [
                "Review relevant lecture notes and textbook sections",
                "Attempt past exam questions on this topic",
                "Discuss with faculty or teaching assistant for clarification",
            ],
        }
        for w in range(1, weeks + 1)
    ]

    return FeedbackResult(
        breakdown=breakdown,
        study_schedule=schedule,
        weak_areas=weak_areas,
        llm_available=False,
        latency_ms=0.0,
        model_used="fallback",
    )


# ---------------------------------------------------------------------------
# Primary public API
# ---------------------------------------------------------------------------

def generate_feedback(
    result: "AssessmentResult",
    ui_inputs: "UIFuzzyInputs | None" = None,
    client: LMStudioClient | None = None,
) -> FeedbackResult:
    """
    Full pipeline: FIS result → weak-area extraction → LLM → FeedbackResult.

    This is the single function called by ``api_server.py``.  It chains
    ``extract_weak_areas`` and ``LMStudioClient.generate`` automatically,
    with graceful degradation if LM Studio is offline.

    Parameters
    ----------
    result : AssessmentResult
        Output of ``FuzzyAssessmentEngine.assess()``.
    ui_inputs : UIFuzzyInputs | None
        If provided, the individual CA / Lab / Final scores are used to
        generate more specific weak-area labels and a richer prompt.
        Pass None for the xAPI batch-scoring path.
    client : LMStudioClient | None
        Optional pre-constructed client (useful for testing with a mock).
        If None, a default client is created.

    Returns
    -------
    FeedbackResult
        Uniform schema — always contains breakdown and study_schedule,
        whether the LLM was available or not.
    """
    if client is None:
        client = LMStudioClient()

    # ── Extract weak areas deterministically ───────────────────────────────
    ca        = float(ui_inputs.continuous_assessment) if ui_inputs else None
    lab_work  = float(ui_inputs.lab_work)              if ui_inputs else None
    final_exam = float(ui_inputs.final_exam)           if ui_inputs else None

    weak_areas = extract_weak_areas(
        crisp_attainment=result.crisp_attainment,
        label=result.label,
        assignment_score=result.assignment_score,
        attendance=result.attendance,
        ca=ca,
        lab_work=lab_work,
        final_exam=final_exam,
    )

    # ── Build prompts ───────────────────────────────────────────────────────
    user_prompt = _build_user_prompt(
        crisp_attainment=result.crisp_attainment,
        label=result.label,
        assignment_score=result.assignment_score,
        attendance=result.attendance,
        weak_areas=weak_areas,
        fired_rules=result.fired_rules,
        ca=ca,
        lab_work=lab_work,
        final_exam=final_exam,
    )

    # ── Call LM Studio ──────────────────────────────────────────────────────
    try:
        parsed, model_id, latency = client.generate(
            system_prompt=_SYSTEM_PROMPT,
            user_prompt=user_prompt,
        )

        # Normalise: LLM may return breakdown/study_schedule at any nesting level
        breakdown      = parsed.get("breakdown", "")
        study_schedule = parsed.get("study_schedule", [])

        if not breakdown:
            raise ValueError("LLM response missing 'breakdown' key.")

        return FeedbackResult(
            breakdown=breakdown,
            study_schedule=study_schedule,
            weak_areas=weak_areas,
            llm_available=True,
            latency_ms=latency,
            model_used=model_id,
        )

    except urllib.error.URLError as exc:
        print(
            f"[agentic] LM Studio network error ({type(exc).__name__}: {exc.reason}) "
            f"— returning rule-based fallback.\n"
            f"          Ensure LM Studio is open and the server is started "
            f"(Developer tab → Start Server)."
        )
        return _build_fallback_feedback(result.crisp_attainment, result.label, weak_areas)

    except (json.JSONDecodeError, ValueError, KeyError) as exc:
        print(f"[agentic] LLM output parse error ({type(exc).__name__}: {exc}) — returning rule-based fallback.")
        return _build_fallback_feedback(result.crisp_attainment, result.label, weak_areas)

    except Exception as exc:
        print(f"[agentic] Unexpected error ({type(exc).__name__}: {exc}) — returning rule-based fallback.")
        return _build_fallback_feedback(result.crisp_attainment, result.label, weak_areas)


# ---------------------------------------------------------------------------
# CLI smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from fuzzy_engine import FuzzyAssessmentEngine
    from ui_bridge    import map_ui_inputs

    print("\n" + "═" * 60)
    print("  Phase 3 — Agentic Feedback Smoke Test")
    print("═" * 60)

    engine = FuzzyAssessmentEngine()

    test_cases = [
        ("Struggling student",     35, 40, 38, 45),
        ("Average student",        60, 65, 58, 78),
        ("High performer",         88, 82, 91, 95),
    ]

    client = LMStudioClient()
    print(f"\n  LM Studio available: {client.is_available()}")

    for description, ca, lab, final, att in test_cases:
        print(f"\n  {'─' * 56}")
        print(f"  [{description}]  CA={ca} | Lab={lab} | Final={final} | Att={att}%")

        ui   = map_ui_inputs(ca, lab, final, att)
        result = engine.assess(ui.assignment_score, ui.attendance)

        print(f"  FIS → crisp={result.crisp_attainment:.2f}%  label={result.label}")

        feedback = generate_feedback(result, ui_inputs=ui, client=client)

        print(f"\n  Weak areas identified:")
        for area in feedback.weak_areas:
            print(f"    • {area}")

        print(f"\n  LLM available : {feedback.llm_available}")
        print(f"  Model used    : {feedback.model_used}")
        print(f"  Latency       : {feedback.latency_ms:.0f} ms")
        print(f"\n  Breakdown (first 300 chars):")
        print(f"    {feedback.breakdown[:300]}…")

    print("\n" + "═" * 60)
